config/routes.rb
require "sidekiq/web"

Sidekiq::Web.use Rack::Auth::Basic do |_, password|
  ActiveSupport::SecurityUtils.secure_compare(
    ::Digest::SHA256.hexdigest(password),
    ::Digest::SHA256.hexdigest(ENV["JOB_ADMIN_PASSWORD"]),
  )
end

Rails.application.routes.draw do
  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    resources :masquerades, param: :username, only: [:show, :destroy]
    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  mount Sidekiq::Web, at: "/jobs"

  get "/auth/github/callback", to: "sessions#create"
  get "/sign_out", to: "sessions#destroy"
  get "/configuration", to: redirect(ENV.fetch("DOCS_URL"), status: 302)
  get "/docs", to: redirect(ENV.fetch("DOCS_URL"), status: 302)
  get "/documentation", to: redirect(ENV.fetch("DOCS_URL"), status: 302)
  get "/faq", to: redirect(ENV.fetch("FAQ_URL"), status: 302)
  get "/help", to: redirect(ENV.fetch("HELP_URL"), status: 302)
  get "/update_billing", to: "application#update_billing"

  resource :account, only: [:show, :update]
  resources :builds, only: [:create, :index]
  resources :deleted_subscriptions, only: [:create]
  resources :github_events, only: [:create]
  resources :owners, only: [:update]
  resources :plans, only: [:index]
  resource :setup, only: [:show]

  resources :repos, only: [:index] do
    with_options(defaults: { format: :json }) do
      resource :activation, only: [:create]
      resource :deactivation, only: [:create]
      resource :subscription, only: [:create, :update, :destroy]
    end

    resources :rebuilds, only: [:create]
  end

  with_options(defaults: { format: :json }) do
    resource :credit_card, only: [:update]
    resources :repo_syncs, only: [:create]
    resource :user, only: [:show]
  end

  %w(404 422 500).each do |status_code|
    get status_code, to: "errors#show", code: status_code
  end

  root to: "home#index"
end

app/models/repo.rb
class Repo < ApplicationRecord
  belongs_to :owner
  has_one :subscription
  has_many :builds, dependent: :destroy
  has_many :memberships, dependent: :destroy
  has_many :users, through: :memberships

  validates :github_id, uniqueness: true, presence: true

  def self.active
    where(active: true)
  end

  def self.find_or_create_with(attributes)
    repo = find_by(github_id: attributes[:github_id]) ||
      find_by(name: attributes[:name]) ||
      Repo.new

    begin
      repo.update!(attributes)
    rescue ActiveRecord::RecordInvalid => error
      report_update_failure(error, attributes)
    end

    repo
  end

  def activate
    update(active: true)
  end

  def deactivate
    update(active: false)
  end

  def stripe_subscription_id
    if subscription
      subscription.stripe_subscription_id
    end
  end

  def total_violations
    builds.sum(:violations_count)
  end

  def remove_membership(user)
    users.destroy(user)
  end

  def users_with_token
    users.where.not(token: nil)
  end

  def public?
    !private?
  end

  private

  def organization
    name && name.split("/").first
  end

  def self.report_update_failure(error, attributes)
    Raven.capture_exception(
      error,
      extra: {
        github_id: attributes[:github_id],
        name: attributes[:name],
      }
    )
  end
  private_class_method :report_update_failure
end

app/controllers/repos_controller.rb
class ReposController < ApplicationController
  def index
    respond_to do |format|
      format.html
      format.json do
        repos = ReposWithMembershipOrSubscriptionQuery.call(current_user)

        render json: repos
      end
    end
  end
end

app/helpers/repos_helper.rb
module ReposHelper
  def switch(repo)
    current_state = repo.active ? 'off' : 'on'
    link_to(current_state, '#', { 'data-github-id' => repo.github_id })
  end

  def has_active_repos?(user)
    user.repos.any? && user.has_active_repos?
  end

  def has_no_builds?(user)
    user.has_active_repos? && user.builds.none?
  end
end

app/views/repos/_github_app.haml
%section.onboarding
  .inner-wrapper.clearfix
    %h1= t("banner.github_app.title")
    .onboarding-steps
      = t("banner.github_app.description_html")

app/views/repos/_onboarding.haml
%section.onboarding
  .inner-wrapper.clearfix
    %h1= t("onboarding.title")
    %ol.onboarding-steps
      %li.step{ class: ("current-step" if current_user.repos.none?) }
        %strong= t("onboarding.step_one_title")
        %p
          = t("onboarding.step_one_desc")
      %li.step{ class: ("current-step" unless has_active_repos?(current_user)) }
        - if has_active_repos?(current_user)
          %strong
            = t "onboarding.step_two_alt_title",
              count: current_user.repos.active.count
        - else
          %strong= t("onboarding.step_two_title")
        %p
          = t("onboarding.step_two_desc")
          = link_to(t("onboarding.account_link"), account_path)
      %li.step{ class: ("current-step" if has_no_builds?(current_user)) }
        %strong= t("onboarding.step_three_title")
        %p= t("onboarding.step_three_desc")

app/views/repos/_onboarding.html.erb
<section class="onboarding">
  <div class="inner-wrapper">
    <h1>
      <%= t("onboarding.title") %>
    </h1>
    <ol class="onboarding-steps">
      <% if current_user.has_active_repos? %>
        <li class="step">
          <h4>
            <%= t("onboarding.step_one_alt_title", count: current_user.repos.active.count ) %>
          </h4>
          <p>
            <%= t("onboarding.step_one_desc") %>
          </p>
        </li>
        <li class="step current-step">
          <h4>
            <%= t("onboarding.step_two_alt_title") %>
          </h4>
          <p>
            <%= t("onboarding.step_two_desc") %>
          </p>
        </li>
      <% else %>
        <li class="step current-step">
          <h4>
            <%= t("onboarding.step_one_title") %>
          </h4>
          <p>
            <%= t("onboarding.step_one_desc") %>
          </p>
        </li>
        <li class="step">
          <h4>
            <%= t("onboarding.step_two_title") %>
          </h4>
          <p>
            <%= t("onboarding.step_two_desc") %>
          </p>
        </li>
      <% end %>
      <li class="step">
        <h4>
          <%= t("onboarding.step_three_title") %>
        </h4>
        <p>
          <%= t("onboarding.step_three_desc") %>
        </p>
      </li>
    </ol>
  </div>
</section>

app/views/repos/index.haml
- content_for :page_title, 'Your Repos'

= render 'settings'

- if display_onboarding?
  = render 'onboarding'
- else
  = render 'github_app'

%section.organization-list{ 'organization-list' => '' }

= javascript_pack_tag "app"
= react_component "App",
  appName: ENV.fetch("GITHUB_APP_NAME"),
  userHasCard: current_user.card_exists?

app/views/repos/index.html.erb
<% content_for :page_title, "Your Repos" %>
<% content_for :header_class, "repo-index" %>
<% content_for :container_class, "repo-index" %>
<%= render "settings" %>
<% if display_onboarding? %>
  <%= render "onboarding" %>
<% end %>
<section class="organization-list"></section>
<%= react_component("ReposContainer",
  authenticity_token: form_authenticity_token,
  has_private_access: current_user.has_access_to_private_repos?,
  userHasCard: current_user.stripe_customer_id.present?)
%>